package %packageName%
{
	import flash.utils.Dictionary;
	import mx.controls.Alert;
	import org.flixel.FlxGroup;
	import org.flixel.FlxTilemap;
	
	/**
	 * Level Name: %className%
	 * Generated By: %generatedBy%
	 *
	 * Tilemap Class: %tilemapClass%
	 *
	 * @author ...
	 * @version ...
	 * @date %generationDate%
	 */
	public class %className% extends FlxGroup
	{
		//{ region Constant graphical asset declarations
		/* Tilesheet graphics */
		%gfxEmbedStatements%
		//} endregion
		
		//{ region Tile index strings
		/* Layer tile data */
		%layerTileData%
		//} endregion
		
		//{ region Tilemap variable declarations
		/* Tilemap declarations */
		%tilemapDeclarations%
		//} endregion
		
		public function %className%() 
		{
			initializeTilemaps();
		}
		
		//{ region Initialization functions
		protected function initializeTilemaps(): void
		{
			%tilemapInitialization%
		}
		//} endregion
		
	}

}