package %packageName%
{
	import flash.utils.Dictionary;
	import mx.controls.Alert;
	import org.flixel.FlxGroup;
	import org.flixel.FlxTilemap;
	
	/**
	 * Level Name: %className%
	 * Generated By: %generatedBy%
	 *
	 * Tilemap Class: %tilemapClass%
	 *
	 * @author ...
	 * @version ...
	 * @date %generationDate%
	 */
	public class %className% extends FlxGroup
	{
		/* Tilesheet graphics */
		%gfxEmbedStatements%
		
		/* Layer tile data */
		%layerTileData%
		
		/* Tilemap declarations */
		%tilemapDeclarations%
		
		public function %className%() 
		{
			initializeTilemaps();
		}
		
		protected function initializeTilemaps(): void
		{
			%tilemapInitialization%
		}
		
	}

}